platform :ios, '11.0'
use_frameworks!

target 'HSBKeyboardNotification_Example' do
  pod 'HSBKeyboardNotification', :path => '../'

  target 'HSBKeyboardNotification_Tests' do
    inherit! :search_paths

    
  end
end
